### ISSUE TITLE
Images arent crroect fro global english version

### ISSUE THREAD

**Issue by Myself-Bloons** [wolfria/ToF_auto_leveling#3]
Had to change them myself :(
But might be hard for some.

**Comment by wolfria** [comment]
I usually play in Japanese and have only been able to verify the English version only briefly, and there is a fear that the most recent update has stopped working.
I would like to verify this when I get some time.

**Comment by Myself-Bloons** [comment]
Sadly Japanase doesn't work either with latest release, I tried it out yesterday they changed quite a few things.

**Comment by wolfria** [comment]
Thanks for the confirmation.
I have reproduced the non-working situation here as well.
Will fix it soon.
I have added a note in the readme that it does not work with the latest version.

**Comment by Myself-Bloons** [comment]
Thank you for your reactivity, the whole flow of Frontier Clash has changed so i's pretty hard to do it when you don't know python, I managed with it being really slow and have to wait at the end for auto tp back. And there is also the problem when nobody activates the switch.
If you have any questions don't hesitate.

**Comment by wolfria** [comment]
Adjusted to work with the latest version (1.5.2).

Thank you.
I am not familiar with Python as it was my first exposure to it when creating the RPA tool.
We have identified the problem if no one activates the switch.
This will be a new issue.

**Comment by wolfria** [comment]
@Myselfish
If you can confirm that it works, may I ask you to close the issue?
If it does not work in your environment, please let us know.

**Comment by Myself-Bloons** [comment]
> @Myselfish If you can confirm that it works, may I ask you to close the issue? If it does not work in your environment, please let us know.

Works but with a fix that I did as I explained in your thread :)
