### ISSUE TITLE
Does not work if no one activates the switch

### ISSUE THREAD

**Issue by wolfria** [wolfria/ToF_auto_leveling#4]
If no one currently presses the switch, the script may not work.
I've been working on other things lately and don't have a lot of time to address this.
Any suggestions that can address this are welcome.

**Comment by Myself-Bloons** [comment]
You did manage to do it with the "challenge fail" recognition. Should it be possible then ?

**Comment by wolfria** [comment]
I checked again and that was a simple fix.
After turning auto on, it will not start the next process until it detects the start of a wave or a failed attempt.
That was verified in solo mode.
It would be appreciated if you could let us know if you detect any new problems.

**Comment by Myself-Bloons** [comment]
Will do !

**Comment by Myself-Bloons** [comment]
Oh yes you should put where we can change the language in main.py or make  prompt ? most people won't know it doesn't work because default is jp ?
Btw it still doesn't work because bygone is in this order : 
![image](https://user-images.githubusercontent.com/38400384/192146592-81c14799-1ab6-4b99-a4e9-de20d566e01e.png)
So old code to find FC.

**Comment by Myself-Bloons** [comment]
```
bygonePhantasmPosition = pyautogui.locateOnScreen(f'./images/en/bygone_phantasm.png' , confidence=0.7)
trainingPosition = pyautogui.locateOnScreen(f'./images/en/training.png' , confidence=0.7)
pyautogui.moveTo(bygonePhantasmPosition)
pyautogui.dragTo(trainingPosition, duration=0.5, button="left")
```

My fix . Don't know if a universal is possible ?

**Comment by wolfria** [comment]
I was not doing void lifts, so I was working under different conditions than you.
I will adopt this method because I can detect any case by calculating from the training position without checking the position of Bygone Phantasm.

**Comment by wolfria** [comment]
> Oh yes you should put where we can change the language in main.py or make prompt ? most people won't know it doesn't work because default is jp ?

At the beginning of the process, the following is done
```
if pyautogui.locateOnScreen(f'./images/en/adventure.png' , confidence=0.5) is not None:
            lang = 'en'
```
This makes the default language JP, but it is automatically recognized and works as EN, so there is no need to modify the code to change the language.

**Comment by wolfria** [comment]
If more languages are added in the future, or if various languages are added, I may modify the advice accordingly, but at this time I have no plans to support languages other than EN myself.

**Comment by wolfria** [comment]
Close the recursion if no one turns on the switch, as it has already been added.
