### ISSUE TITLE
can you add auto checking assist mod

### ISSUE THREAD

**Issue by midoom** [wolfria/ToF_auto_leveling#5]
hello can you add auto assist mod if you don't want use your try for normal mode. thx
        

>         assistPosition = pyautogui.locateOnScreen(f'./images/{lang}/assist.png' , confidence=0.8)
>         if assistPosition is not None:
>             pyautogui.click(assistPosition)
>         print('Assist mod!')
>         time.sleep(1)

**Comment by wolfria** [comment]
Sorry. I have 0 Attempts on Frontier Clash right now, so I can't test it. 
I will be able to work on it once I get my Attempts back up.

**Comment by wolfria** [comment]
Finally got some time to add that.
